layout_spectrum: 0.1305566153023392
typography_spectrum: 0.12048497307114303
color:
  brandStrength: 0.35159473144449294
  lightness: 0.2552553452551365
  saturation: 0.2366266716271639
  rhythmicContrast: 0.2935198461636901
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
name: DigitalArson
title: Sumthin Normal
